### ISSUE TITLE
Validation issue on login page

### ISSUE THREAD

**Issue by ankitcedcoss** [stores-cedcommerce/Internal---MicheleBenjamin-store-dev-Speed-4April#13]
Bug - when user click on any area on page then validation gets appear on email field.
Exp - Validation should show when user click on email field and leaves its blank and moves on next text field.
Ref link - https://drive.google.com/file/d/179I8cQpFfzU03_4ZfQlj_w2CxchXA50Z/view

**Comment by dev-amitkumarbharti1** [comment]
here focus event is used this is not an issue

**Comment by ankitcedcoss** [comment]
Bug - Not Fixed

@dev-amitkumarbharti1 Please add correct validation message on field
For email field -
- if blank - Email is required
- invalid format - incorrect email format
- First name - First name is required
- Password  - Password is required (char length)

Please add on Login, Reset password and create account pages.
https://drive.google.com/file/d/1RIictIP0YgxK5Pc0DWXz3RnyXSLt52Rg/view

**Comment by Arpan012** [comment]
error messages validation part is not working fine , when I have not entered anything no error message , after entering first name still there is no error message

**Comment by Arpan012** [comment]
Uploading michellebenjamin.mp4…
