### ISSUE TITLE
Header navigations button not working.

### ISSUE THREAD

**Issue by ankitcedcoss** [stores-cedcommerce/Internal---MicheleBenjamin-store-dev-Speed-4April#25]
Bug - Header navigation button not working.
Exp - button should redirect user to its respective page.
Ref Link - 
- https://drive.google.com/file/d/1kYQMbHSrisYJu9q3SwpfHKkxabKBjjFf/view
- https://drive.google.com/file/d/10HCJPX_X8RAcePjeNWYUaUWWytvpCYeo/view
- https://drive.google.com/file/d/1BQUesKaO8szYJ39LhIBf_j5M-yWu2TOO/view

Please check all links

**Comment by dev-amitkumarbharti1** [comment]
Updated the photography link once client provide the commission page link I will add them

**Comment by ankitcedcoss** [comment]
Bug Fixed
