### ISSUE TITLE
UI issue on new banner image.

### ISSUE THREAD

**Issue by ankitcedcoss** [stores-cedcommerce/Internal---MicheleBenjamin-store-dev-Speed-4April#41]
Bug - Logo on banner hiding behind navigation button and contact button UI issue.
Exp - Logo on banner should not get hide and create button UI for contact button on banner
Ref Link - 
- https://nimb.ws/61pYET
- https://nimb.ws/dxpstC
- https://nimb.ws/794jSb

**Comment by ui-neelu** [comment]
https://nimb.ws/61pYET 
Done


Not Required
https://nimb.ws/dxpstC
https://nimb.ws/794jSb

**Comment by ankitcedcoss** [comment]
Fixed issue - https://nimb.ws/61pYET
