### ISSUE TITLE
Product page description accordian heading font size UI issue

### ISSUE THREAD

**Issue by ankitcedcoss** [stores-cedcommerce/Internal---MicheleBenjamin-store-dev-Speed-4April#8]
Bug - Product page description according heading and sub heading font size UI issue.
Exp - Description heading text should be 18px and sub heading should be 16px.
Ref Link - https://drive.google.com/file/d/1K3zc5vFc1iULYhlLLo0qWfs_ttg-LrFP/view

**Comment by dev-amitkumarbharti1** [comment]
All the description text and html is coming directly from the backend it is not possible to edit every product description manually

**Comment by ankitcedcoss** [comment]
Closed on Not Required
