### ISSUE TITLE
UI issue in wishlist

### ISSUE THREAD

**Issue by ankitcedcoss** [stores-cedcommerce/Internal---MicheleBenjamin-store-dev-Speed-4April#9]
Bug - Hover effect not working on Add to cart button and showing unmatched color on buttons.
Exp - Need to add hover effect on add to cart button
- User store color for login button text and add all and remove from wishlist button text.
Ref Link - https://drive.google.com/file/d/1lq73__L0a3YpWEMC6FaOyS5Nbb_Y0EJi/view

**Comment by dev-amitkumarbharti1** [comment]
We have changed the color and designed the button too much customization is not possible because the whole page is coming from app

**Comment by ankitcedcoss** [comment]
Bug Fixed
https://nimb.ws/l1oW7M
